services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\WarningOnForeign\:
    resource: '../../../Classes/Features/WarningOnForeign/*'

  In2code\In2publishCore\Features\WarningOnForeign\Service\HeaderWarningColorRenderer:
    public: true
