services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $localDatabase: '@In2code.In2publishCore.Database.Local'
      $foreignDatabase: '@In2code.In2publishCore.Database.Foreign'

  In2code\In2publishCore\Features\SimpleOverviewAndAjax\:
    resource: '../../../Classes/Features/SimpleOverviewAndAjax/*'
