services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\SimpleOverviewAndAjax\:
    resource: '../../../Classes/Features/SimpleOverviewAndAjax/*'
