services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\ContextMenuPublishEntry\:
    resource: '../../../Classes/Features/ContextMenuPublishEntry/*'

  In2code\In2publishCore\Features\ContextMenuPublishEntry\Controller\PublishPageAjaxController:
    public: true
